---
- name: this is test playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd 
    yum: 
      name: httpd
      state: present
    notify: start httpd

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
