---
- name: this is test playbook
  hosts: all
  become: true
  tasks:
  - name: install package httpd
    yum:
      name: httpd
      state: present

  - name: start httpd service
    service:
      name: httpd
      state: started
