---
- name: install httpd
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd

- name: install apache
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache

- name: copy index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777 
