---
- name: start httpd
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: start apache
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"
